# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overriden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to. Example value: less
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    pv: pr view
    pvw: pr view -w
    pc: pr create
    pcw: pr create -w
    pl: pr list
    pcd: pr create --draft --fill
    ps: pr list --state all --search
    d: dash
    rv: repo view
    rvw: repo view -w
version: "1"
