#!/usr/bin/env zsh

source_dir=${CHEZMOI_SOURCE_DIR:-${0:A:h}}

source "$source_dir/exact_private_bin/_common.zsh"

grep -q pam_tid /etc/pam.d/sudo && exit 0

log_message "Enabling Touch ID in sudo"

echo auth sufficient pam_tid.so | cat - /etc/pam.d/sudo | sudo tee /etc/pam.d/sudo > /dev/null
