#!/usr/bin/env zsh

set +o pipefail

source_dir=${CHEZMOI_SOURCE_DIR:-${0:A:h}}
file=$source_dir/${CHEZMOI_SOURCE_FILE:-${0:t}}

source "$source_dir/exact_private_bin/_common.zsh"

if command -v atuin &> /dev/null; then
  exec_unless_recently_modified $file "atuin update || true"
else
  curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh -s -- --non-interactive
fi
