#!/usr/bin/env zsh

source_dir=${CHEZMOI_SOURCE_DIR:-${0:A:h}}
file=$source_dir/${CHEZMOI_SOURCE_FILE:-${0:t}}

source "$source_dir/exact_private_bin/_common.zsh"

set +o pipefail

eval "$(mise hook-env)"

exec_unless_recently_modified $file "gem update --system; yes | gem update -f ; yes | gem cleanup"
